#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Spring cloud를 통해 변경이 가능한 요소들을 정의한다.
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: gateway-local
  cloud:
    gateway:
      routes:
      - id: order
        uri: lb://ORDER-SERVICE-LOCAL
        predicates:
          - Path=/api/v1/orders/**
      - id: customer
        uri: lb://CUSTOMER-SERVICE-LOCAL
        predicates:
          - Path=/api/v1/customer/**
      - id: chat
        uri: lb://CHAT-SERVICE
        predicates:
          - Path=/api/v1/chat/**

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Endpoint output options for Hystrix Stream
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
